spring:
  datasource:
    username: root
    password: Zeng19980715**
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.zeng.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml